[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
